catalog:
  name: "Kibanew"
  version: "5.3.0"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"
