.catalog:
  name: "ELK-Stack"
  version: "5.3.0-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true
    - variable: "elastic-node-1-label"
      label: "Elastic node 1 will be deployed on the host with this label"
      description: "Elastic node 1 will be deployed on the host with this label"
      type: "string"
      default: "node1"
      required: true
    - variable: "elastic-node-2-label"
      label: "Elastic node 2 will be deployed on the host with this label"
      description: "Elastic node 2 will be deployed on the host with this label"
      type: "istring"
      default: "node2" 
      required: true

nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601
