version: '2'
catalog:
  name: "ELK Stack"
  version: "5.6.3"
  description: "Full ELK stack for easy data analysis" 
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true

nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601

