version: '2'
catalog:
  name: "ELK Stack"
  version: "5.6.3"
  description: "Full ELK stack for easy data analysis" 
services:
  lb:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 80
        target_port: 5601
        service: kibana
