.catalog:
  name: "ELKibana"
  version: "5.3.0-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true
l
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601
